const practice_info = {
    key_press: [
        {
            picture: "images/13_50_different.jpg",
            number: 13,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
						
        },
        {
            picture: "images/13_50_same.jpg",
            number: 13,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/13_150_different.jpg",
            number: 13,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/13_150_same.jpg",
            number: 13,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/14_50_different.jpg",
            number: 14,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/14_50_same.jpg",
            number: 14,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/14_150_different.jpg",
            number: 14,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/14_150_same.jpg",
            number: 14,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
			
        },
        {
            picture: "images/15_50_different.jpg",
            number: 15,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
			
        },
        {
            picture: "images/15_50_same.jpg",
            number: 15,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
			
        },
        {
            picture: "images/15_150_different.jpg",
            number: 15,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
			
        },
        {
            picture: "images/15_150_same.jpg",
            number: 15,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
			
        },
    ],
};

const main_info = {
    key_press: [
        {
            picture: "images/1_50_same.jpg",
            number: 1,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 

        },
        {
            picture: "images/1_50_different.jpg",
            number: 1,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',

        },
        {
            picture: "images/1_150_same.jpg",
            number: 1,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/1_150_different.jpg",
            number: 1,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/2_50_same.jpg",
            number: 2,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/2_50_different.jpg",
            number: 2,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/2_150_same.jpg",
            number: 2,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/2_150_different.jpg",
            number: 2,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },

        {
            picture: "images/3_50_same.jpg",
            number: 3,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/3_50_different.jpg",
            number: 3,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/3_150_same.jpg",
            number: 3,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/3_150_different.jpg",
            number: 3,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },

        {
            picture: "images/4_50_same.jpg",
            number: 4,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/4_50_different.jpg",
            number: 4,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/4_150_same.jpg",
            number: 4,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/4_150_different.jpg",
            number: 4,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },

        {
            picture: "images/5_50_same.jpg",
            number: 5,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/5_50_different.jpg",
            number: 5,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/5_150_same.jpg",
            number: 5,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/5_150_different.jpg",
            number: 5,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/6_50_same.jpg",
            number: 6,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/6_50_different.jpg",
            number: 6,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/6_150_same.jpg",
            number: 6,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/6_150_different.jpg",
            number: 6,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },

        {
            picture: "images/7_50_same.jpg",
            number: 7,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/7_50_different.jpg",
            number: 7,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/7_150_same.jpg",
            number: 7,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/7_150_different.jpg",
            number: 7,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },

        {
            picture: "images/8_50_same.jpg",
            number: 8,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/8_50_different.jpg",
            number: 8,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/8_150_same.jpg",
            number: 8,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/8_150_different.jpg",
            number: 8,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },

        {
            picture: "images/9_50_same.jpg",
            number: 9,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/9_50_different.jpg",
            number: 9,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/9_150_same.jpg",
            number: 9,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/9_150_different.jpg",
            number: 9,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/10_50_same.jpg",
            number: 10,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/10_50_different.jpg",
            number: 10,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/10_150_same.jpg",
            number: 10,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/10_150_different.jpg",
            number: 10,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different', 
        },
        {
            picture: "images/11_50_same.jpg",
            number: 11,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/11_50_different.jpg",
            number: 11,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/11_150_same.jpg",
            number: 11,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/11_150_different.jpg",
            number: 11,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/12_50_same.jpg",
            number: 12,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/12_50_different.jpg",
            number: 12,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/12_150_same.jpg",
            number: 12,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
        {
            picture: "images/12_150_different.jpg",
            number: 12,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			f: 'same',
			j: 'different',
        },
    ],
};